<a href="https://colab.research.google.com/github/starkz11/TensorFlow/blob/main/Tensor_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction To **Tensors**

In [ ]:
#import Tensorflow

import tensorflow as tf
print(tf.__version__)#command Helps us to find version of tensorflow

2.12.0


# Creating with tf.**constant**

In [ ]:
#creating tensors with tf.constant()---tf.constant() cannot change in future

scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#create ndim--no.of dimensions
scalar.ndim

0

In [ ]:
#creating vectors
vectors=tf.constant([1,2,3,4])
print(vectors)

print(vectors.shape)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
(4,)


In [ ]:
#dimension of vector
vectors.ndim

1

In [ ]:
#creating a matrix

matrix=tf.constant([
    [2,3],
    [211,12]
])
matrix
print(matrix.ndim)
print(matrix.shape)

2
(2, 2)


In [ ]:
#ceate another matrix with datatype(dtype)
another_matrix=tf.constant([
    [2,3,4],
    [2,32,33],
    [2,234,23]
],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[  2.,   3.,   4.],
       [  2.,  32.,  33.],
       [  2., 234.,  23.]], dtype=float16)>

In [ ]:
#ndim
another_matrix.ndim

2

In [ ]:
#creating tensors

tensors=tf.constant([
    [
        [1,2,4],
        [1,2,32],
        [34,323,112],
        [6,523,23],
    ],
    [
        [1,2,4],
        [1,2,32],
        [34,323,112],
        [6,523,23],
    ],
    [
        [1,2,4],
        [1,2,32],
        [34,323,112],
        [6,523,23],
    ]
])

tensors

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[  1,   2,   4],
        [  1,   2,  32],
        [ 34, 323, 112],
        [  6, 523,  23]],

       [[  1,   2,   4],
        [  1,   2,  32],
        [ 34, 323, 112],
        [  6, 523,  23]],

       [[  1,   2,   4],
        [  1,   2,  32],
        [ 34, 323, 112],
        [  6, 523,  23]]], dtype=int32)>

In [ ]:
tensors.ndim

4

# Creating Tensors with tf.**Variable**

In [ ]:
changable_tensor=tf.Variable([4,2])
unchangable_tensor=tf.constant([4,2])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 2], dtype=int32)>)

In [ ]:
changable_tensor[0]=2 #don't use this type of format to change values of tensors
changable_tensor

In [ ]:
changable_tensor[0].assign(6)# use this type of format to change values of tensors
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([6, 2], dtype=int32)>

In [ ]:
unchangable_tensor[0].assign(4)#cannot change the values of tf.constant
unchangable_tensor

# Create tensors with random


In [ ]:
g1 = tf.random.Generator.from_seed(1)
print(g1.normal(shape=[3, 3]))
g2 = tf.random.get_global_generator()
print(g2.normal(shape=[2, 3]))

tf.Tensor(
[[ 0.43842274 -0.53439844 -0.07710262]
 [ 1.5658046  -0.1012345  -0.2744976 ]
 [ 1.4204658   1.2609464  -0.43640924]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.725465    1.9638231  -2.3631039 ]
 [ 0.77367747  1.5859905   1.0308619 ]], shape=(2, 3), dtype=float32)
